/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arr.h"


void
sum_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	intarr  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SUM_PROG, SUM_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	add_1_arg.n = 4;
	add_1_arg.arr[0] = 10;
	add_1_arg.arr[1] = 11;
	add_1_arg.arr[2] = 32;
	add_1_arg.arr[3] = 44;
	
	result_1 = add_1(&add_1_arg, clnt);
	
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("result = %d\n", *result_1);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	sum_prog_1 (host);
exit (0);
}
