/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arr.h"

int *
add_1_svc(intarr *argp, struct svc_req *rqstp)
{
	static int  result;

	result = 0;
	for(int i=0; i<argp->n; i++) {
		result += argp->arr[i];
	}

	return &result;
}
